### ISSUE TITLE
Will crash if file or directory does not exist

### ISSUE THREAD

**Issue by matsilva** [matsilva/installfont#1]
Need to check for file or directory first and handle any errors.

```
fs.js:689
  return binding.stat(pathModule._makeLong(path));
                 ^
Error: ENOENT, no such file or directory '/home/msilva/builds/54d0cd886426e78125edabbf/54d0d08db6166f333badd265/fonts'
    at Object.fs.statSync (fs.js:689:18)
    at isFolder (/home/msilva/RenderEffects/re.buildprocessor/node_modules/installfont/lib/installfont.js:32:18)
    at module.exports (/home/msilva/RenderEffects/re.buildprocessor/node_modules/installfont/lib/installfont.js:48:6)
    at ChildProcess.<anonymous> (/home/msilva/RenderEffects/re.buildprocessor/lib/index.js:187:16)
    at ChildProcess.EventEmitter.emit (events.js:117:20)
    at maybeClose (child_process.js:743:16)
    at Socket.<anonymous> (child_process.js:956:11)
    at Socket.EventEmitter.emit (events.js:95:17)
    at Pipe.close (net.js:466:12)
```

**Comment by matsilva** [comment]
Fixed in: https://github.com/matsilva/installfont/pull/4
